version: "3.7"
services:
  frontend:
    build:
      context: frontend
      target: development
      args:
        - GIT_USERNAME= canbefree
        - GIT_EMAIL=452198757@qq.com
    # command: sleep infinity
    privileged: true
    ports:
      - 8080:3000
    user: 1000:1000
    networks:
      - app_net

  bff:
    build:
      context: bff
    networks:
      - app_net
    
secrets:
  credential:
    file: secrets/credential/test.tls

networks:
    app_net:
        external: true